kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  - sleep 20

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  - sleep 50
